### Create Task
POST http://127.0.0.1:8000/tasks
Content-Type: application/json

{
    "name": "Manutentionnne",
    "description": "Nothing"
}

### List Tasks
GET http://127.0.0.1:8000/tasks

### Update Tasks
PUT http://127.0.0.1:8000/tasks/873
Content-Type: application/json

{
    "id": 89,
    "name": "Testes",
    "description": "Testando"
}

### Delete Tasks
DELETE http://127.0.0.1:8000/tasks/87231
