### Create Task 01
POST http://127.0.0.1:8000/tasks
Content-Type: application/json

{
    "id": 1,
    "name": "Planejamento",
    "checked": false
}

### Create Task 02
POST http://127.0.0.1:8000/tasks
Content-Type: application/json

{
    "id": 2,
    "name": "Análise",
    "checked": false
}

### List Tasks
GET http://127.0.0.1:8000/tasks
