### Create Task 01
POST http://127.0.0.1:8000/tasks
Content-Type: application/json

{
    "id": 1,
    "name": "Planejamento"
}

### Create Task 02
POST http://127.0.0.1:8000/tasks
Content-Type: application/json

{
    "id": 2,
    "name": "Analise"
}

### List Tasks
GET http://127.0.0.1:8000/tasks

### Update Tasks
PUT http://127.0.0.1:8000/tasks/2
Content-Type: application/json

{
    "id": 2,
    "name": "Analysis"
}
